; #FUNCTION# ====================================================================================================================
; Name ..........: CGB GUI Design
; Description ...: This file Includes GUI Design
; Syntax ........:
; Parameters ....: None
; Return values .: None
; Author ........: GKevinOD (2014)
; Modified ......: DkEd, Hervidero (2015)
; Remarks .......: This file is part of ClashGameBot. Copyright 2015
;                  ClashGameBot is distributed under the terms of the GNU GPL
; Related .......:
; Link ..........:
; Example .......: No
; ===============================================================================================================================

;~ -------------------------------------------------------------
;~ Donate Tab
;~ -------------------------------------------------------------
$tabDonate = GUICtrlCreateTabItem("Donate")
	Local $x = 30, $y = 150
	$grpDonation = GUICtrlCreateGroup("Ask for Clan Castle Troops", $x - 20, $y - 20, 450, 65)
		GUICtrlCreateIcon($pIconLib, $eIcnCC, $x - 5, $y, 32, 32, $BS_ICON)
		$chkRequest = GUICtrlCreateCheckbox("Request for:", $x + 35, $y + 5, -1, -1)
			GUICtrlSetOnEvent(-1, "chkRequest")
		$txtRequest = GUICtrlCreateInput("Anything please", $x + 115, $y + 5, 305, -1)
			GUICtrlSetState(-1, $GUI_DISABLE)
			GUICtrlSetTip(-1, "This text is used on your request for troops in the Clan chat.")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

$y += 70
$grpTroopselection = GUICtrlCreateGroup("Donate Troops Selection Menu", $x - 20, $y - 20, 450, 110)
$x -=2
	$lblBtnBarbarians = GUICtrlCreateLabel("", $x - 12, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnBarbarians = GUICtrlCreateButton("Barbarians", $x - 10, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonBarbarian, 1)
		GUICtrlSetOnEvent(-1, "btnDonateBarbarians")
	$lblBtnArchers = GUICtrlCreateLabel("", $x + 28, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnArchers = GUICtrlCreateButton("Archers", $x + 30, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonArcher, 1)
		GUICtrlSetOnEvent(-1, "btnDonateArchers")
	$lblBtnGiants = GUICtrlCreateLabel("", $x + 68, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnGiants = GUICtrlCreateButton("Giants", $x + 70, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonGiant, 1)
		GUICtrlSetOnEvent(-1, "btnDonateGiants")
	$lblBtnGoblins = GUICtrlCreateLabel("", $x + 108, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnGoblins = GUICtrlCreateButton("Goblins", $x + 110, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonGoblin, 1)
		GUICtrlSetOnEvent(-1, "btnDonateGoblins")
	$lblBtnWallBreakers = GUICtrlCreateLabel("", $x + 148, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnWallBreakers = GUICtrlCreateButton("WallBreakers", $x + 150, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonWallBreaker, 1)
		GUICtrlSetOnEvent(-1, "btnDonateWallBreakers")

	$btnBlacklist = GUICtrlCreateButton("Blacklist", $x + 191, $y + 24, 32, 32, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonBlacklist, 1)
		GUICtrlSetOnEvent(-1, "btnDonateBlacklist")

	$lblBtnMinions = GUICtrlCreateLabel("", $x + 223, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnMinions = GUICtrlCreateButton("Minions", $x + 225, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonMinion, 1)
		GUICtrlSetOnEvent(-1, "btnDonateMinions")
	$lblBtnHogRiders = GUICtrlCreateLabel("", $x + 263, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnHogRiders = GUICtrlCreateButton("HogRiders", $x + 265, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonHogRider, 1)
		GUICtrlSetOnEvent(-1, "btnDonateHogRiders")
	$lblBtnValkyries = GUICtrlCreateLabel("", $x + 303, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnValkyries = GUICtrlCreateButton("Valkyries", $x+ 305, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonValkyrie, 1)
		GUICtrlSetOnEvent(-1, "btnDonateValkyries")

$y += 40
	$lblBtnBalloons = GUICtrlCreateLabel("", $x - 12, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnBalloons = GUICtrlCreateButton("Balloons", $x - 10, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonBalloon, 1)
		GUICtrlSetOnEvent(-1, "btnDonateBalloons")
	$lblBtnWizards = GUICtrlCreateLabel("", $x + 28, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnWizards = GUICtrlCreateButton("Wizards", $x + 30, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonWizard, 1)
		GUICtrlSetOnEvent(-1, "btnDonateWizards")
	$lblBtnHealers = GUICtrlCreateLabel("", $x + 68, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnHealers = GUICtrlCreateButton("Healers", $x + 70, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonHealer, 1)
		GUICtrlSetOnEvent(-1, "btnDonateHealers")
	$lblBtnDragons = GUICtrlCreateLabel("", $x + 108, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnDragons = GUICtrlCreateButton("Dragons", $x + 110, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonDragon, 1)
		GUICtrlSetOnEvent(-1, "btnDonateDragons")
	$lblBtnPekkas = GUICtrlCreateLabel("", $x + 148, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnPekkas = GUICtrlCreateButton("Pekkas", $x + 150, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonPekka, 1)
		GUICtrlSetOnEvent(-1, "btnDonatePekkas")

	$lblBtnGolems = GUICtrlCreateLabel("", $x + 223, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnGolems = GUICtrlCreateButton("Golems", $x + 225, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonGolem, 1)
		GUICtrlSetOnEvent(-1, "btnDonateGolems")
	$lblBtnWitches = GUICtrlCreateLabel("", $x + 263, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnWitches = GUICtrlCreateButton("Witches", $x+ 265, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonWitch, 1)
		GUICtrlSetOnEvent(-1, "btnDonateWitches")
	$lblBtnLavaHounds = GUICtrlCreateLabel("", $x + 303, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnLavaHounds = GUICtrlCreateButton("LavaHounds", $x + 305, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonLavaHound, 1)
		GUICtrlSetOnEvent(-1, "btnDonateLavaHounds")

	;;; Custom Combination Donate by ChiefM3
	$lblBtnCustom = GUICtrlCreateLabel("", $x + 363, $y - 22, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnCustom = GUICtrlCreateButton("Custom", $x + 365, $y - 20, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonCustom, 1) ;;; cross swords icon
		GUICtrlSetOnEvent(-1, "btnDonateCustom")

$x += 2
$y += 75
	$grpBarbarians = GUICtrlCreateGroup("Barbarians", $x - 20, $y - 20, 450, 190)
		$picDonateBarbarians = GUICtrlCreateIcon($pIconLib, $eIcnDonBarbarian, $x + 215, $y, 64, 64, $BS_ICON)
		$chkDonateBarbarians = GUICtrlCreateCheckbox("Donate Barbarians", $x + 285, $y + 10, -1, -1)
			GUICtrlSetTip(-1, "Check this to donate Barbarians if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateBarbarians")
		$chkDonateAllBarbarians = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetTip(-1, "Check this to donate Barbarians to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllBarbarians")
		$lblDonateBarbarians = 	GUICtrlCreateLabel("Keywords for donating Barbarians:", $x - 5, $y + 5, -1, -1)
		$txtDonateBarbarians = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetData(-1, StringFormat("barbarians\r\nbarb"))
			GUICtrlSetTip(-1, "Keywords for donating Barbarians")
		$lblBlacklistBarbarians = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
		$txtBlacklistBarbarians = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no barbarians\r\nno barb\r\nbarbarians no\r\nbarb no"))
			GUICtrlSetTip(-1, "Blacklist for donating Barbarians")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpArchers = GUICtrlCreateGroup("Archers", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateArchers = GUICtrlCreateIcon($pIconLib, $eIcnDonArcher, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateArchers = GUICtrlCreateCheckbox("Donate Archers", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Archers if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateArchers")
		$chkDonateAllArchers = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Archers to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllArchers")
		$lblDonateArchers = 	GUICtrlCreateLabel("Keywords for donating Archers:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateArchers = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("archers\r\narch"))
			GUICtrlSetTip(-1, "Keywords for donating Archers")
		$lblBlacklistArchers = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistArchers = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no archers\r\nno arch\r\narchers no\r\narch no"))
			GUICtrlSetTip(-1, "Blacklist for donating Archers")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpGiants = GUICtrlCreateGroup("Giants", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateGiants = GUICtrlCreateIcon($pIconLib, $eIcnDonGiant, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateGiants = GUICtrlCreateCheckbox("Donate Giants", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Giants if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateGiants")
		$chkDonateAllGiants = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Giants to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllGiants")
		$lblDonateGiants = 	GUICtrlCreateLabel("Keywords for donating Giants:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateGiants = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("giants\r\ngiant\r\nany\r\nreinforcements"))
			GUICtrlSetTip(-1, "Keywords for donating Giants")
		$lblBlacklistGiants = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistGiants = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no giants\r\ngiants no"))
			GUICtrlSetTip(-1, "Blacklist for donating Giants")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpGoblins = GUICtrlCreateGroup("Goblins", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateGoblins = GUICtrlCreateIcon($pIconLib, $eIcnDonGoblin, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateGoblins = GUICtrlCreateCheckbox("Donate Goblins", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Goblins if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateGoblins")
		$chkDonateAllGoblins = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Goblins to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllGoblins")
		$lblDonateGoblins = 	GUICtrlCreateLabel("Keywords for donating Goblins:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateGoblins = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("goblins\r\ngoblin"))
			GUICtrlSetTip(-1, "Keywords for donating Goblins")
		$lblBlacklistGoblins = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistGoblins = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no goblins\r\ngoblins no"))
			GUICtrlSetTip(-1, "Blacklist for donating goblins")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpWallBreakers = GUICtrlCreateGroup("Wall Breakers", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateWallBreakers = GUICtrlCreateIcon($pIconLib, $eIcnDonWallBreaker, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateWallBreakers = GUICtrlCreateCheckbox("Donate Wall Breakers", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Wall Breakers if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateWallBreakers")
		$chkDonateAllWallBreakers = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Wall Breakers to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllWallBreakers")
		$lblDonateWallBreakers = 	GUICtrlCreateLabel("Keywords for donating Wall Breakers:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateWallBreakers = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("wall breakers\r\nbreaker"))
			GUICtrlSetTip(-1, "Keywords for donating Wall Breakers")
		$lblBlacklistWallBreakers = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistWallBreakers = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no wall breakers\r\nwall breakers no"))
			GUICtrlSetTip(-1, "Blacklist for donating Wall Breakers")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpBalloons = GUICtrlCreateGroup("Balloons", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateBalloons = GUICtrlCreateIcon($pIconLib, $eIcnDonBalloon, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateBalloons = GUICtrlCreateCheckbox("Donate Balloons", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Balloons if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateBalloons")
		$chkDonateAllBalloons = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Balloons to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllBalloons")
		$lblDonateBalloons = 	GUICtrlCreateLabel("Keywords for donating Balloons:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateBalloons = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("balloons\r\nballoon"))
			GUICtrlSetTip(-1, "Keywords for donating Balloons")
		$lblBlacklistBalloons = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistBalloons = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no balloons\r\nballoons no"))
			GUICtrlSetTip(-1, "Blacklist for donating Balloons")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpWizards = GUICtrlCreateGroup("Wizards", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateWizards = GUICtrlCreateIcon($pIconLib, $eIcnDonWizard, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateWizards = GUICtrlCreateCheckbox("Donate Wizards", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Wizards if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateWizards")
		$chkDonateAllWizards = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Wizards to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllWizards")
		$lblDonateWizards = 	GUICtrlCreateLabel("Keywords for donating Wizards:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateWizards = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("wizards\r\nwizard"))
			GUICtrlSetTip(-1, "Keywords for donating Wizards")
		$lblBlacklistWizards = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistWizards = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no wizards\r\nwizards no"))
			GUICtrlSetTip(-1, "Blacklist for donating Wizards")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpHealers = GUICtrlCreateGroup("Healers", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateHealers = GUICtrlCreateIcon($pIconLib, $eIcnDonHealer, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateHealers = GUICtrlCreateCheckbox("Donate Healers", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Healers if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateHealers")
		$chkDonateAllHealers = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Healers to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllHealers")
		$lblDonateHealers = 	GUICtrlCreateLabel("Keywords for donating Healers:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateHealers = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("healer"))
			GUICtrlSetTip(-1, "Keywords for donating Healers")
		$lblBlacklistHealers = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistHealers = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no healer\r\nhealer no"))
			GUICtrlSetTip(-1, "Blacklist for donating Healers")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpDragons = GUICtrlCreateGroup("Dragons", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateDragons = GUICtrlCreateIcon($pIconLib, $eIcnDonDragon, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateDragons = GUICtrlCreateCheckbox("Donate Dragons", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Dragons if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateDragons")
		$chkDonateAllDragons = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Dragons to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllDragons")
		$lblDonateDragons = 	GUICtrlCreateLabel("Keywords for donating Dragons:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateDragons = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("dragon"))
			GUICtrlSetTip(-1, "Keywords for donating Dragons")
		$lblBlacklistDragons = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistDragons = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no dragon\r\ndragon no"))
			GUICtrlSetTip(-1, "Blacklist for donating Dragons")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpPekkas = GUICtrlCreateGroup("P.E.K.K.A.s", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonatePekkas = GUICtrlCreateIcon($pIconLib, $eIcnDonPekka, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonatePekkas = GUICtrlCreateCheckbox("Donate P.E.K.K.A.s", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate P.E.K.K.A.s if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonatePekkas")
		$chkDonateAllPekkas = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate P.E.K.K.A.s to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllPekkas")
		$lblDonatePekkas = 	GUICtrlCreateLabel("Keywords for donating P.E.K.K.A.s:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonatePekkas = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("PEKKA\r\npekka"))
			GUICtrlSetTip(-1, "Keywords for donating P.E.K.K.A.s")
		$lblBlacklistPekkas = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistPekkas = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no PEKKA\r\npekka no"))
			GUICtrlSetTip(-1, "Blacklist for donating P.E.K.K.A.s")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpMinions = GUICtrlCreateGroup("Minions", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateMinions = GUICtrlCreateIcon($pIconLib, $eIcnDonMinion, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateMinions = GUICtrlCreateCheckbox("Donate Minions", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Minions if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateMinions")
		$chkDonateAllMinions = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Minions to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllMinions")
		$lblDonateMinions = 	GUICtrlCreateLabel("Keywords for donating Minions:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateMinions = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("minions\r\nminion"))
			GUICtrlSetTip(-1, "Keywords for donating Minions")
		$lblBlacklistMinions = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistMinions = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no minions\r\nminions no"))
			GUICtrlSetTip(-1, "Blacklist for donating Minions")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpHogRiders = GUICtrlCreateGroup("Hog Riders", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateHogRiders = GUICtrlCreateIcon($pIconLib, $eIcnDonHogRider, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateHogRiders = GUICtrlCreateCheckbox("Donate Hog Riders", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Hog Riders if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateHogRiders")
		$chkDonateAllHogRiders = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Hog Riders to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllHogRiders")
		$lblDonateHogRiders = 	GUICtrlCreateLabel("Keywords for donating Hog Riders:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateHogRiders = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("hogriders\r\nhogs\r\nhog"))
			GUICtrlSetTip(-1, "Keywords for donating Hog Riders")
		$lblBlacklistHogRiders = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistHogRiders = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no hogs\r\nhog no"))
			GUICtrlSetTip(-1, "Blacklist for donating Hog Riders")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpValkyries = GUICtrlCreateGroup("Valkyries", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateValkyries = GUICtrlCreateIcon($pIconLib, $eIcnDonValkyrie, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateValkyries = GUICtrlCreateCheckbox("Donate Valkyries", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Valkyries if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateValkyries")
		$chkDonateAllValkyries = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Valkyries to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllValkyries")
		$lblDonateValkyries = 	GUICtrlCreateLabel("Keywords for donating Valkyries:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateValkyries = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("valkyries\r\nvalkyrie"))
			GUICtrlSetTip(-1, "Keywords for donating Valkyries")
		$lblBlacklistValkyries = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistValkyries = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no valkyries\r\nvalkyries no"))
			GUICtrlSetTip(-1, "Blacklist for donating Valkyries")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpGolems = GUICtrlCreateGroup("Golems", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateGolems = GUICtrlCreateIcon($pIconLib, $eIcnDonGolem, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateGolems = GUICtrlCreateCheckbox("Donate Golems", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Golems if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateGolems")
		$chkDonateAllGolems = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Golems to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllGolems")
		$lblDonateGolems = 	GUICtrlCreateLabel("Keywords for donating Golems:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateGolems = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("golem"))
			GUICtrlSetTip(-1, "Keywords for donating Golems")
		$lblBlacklistGolems = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistGolems = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no golem\r\ngolem no"))
			GUICtrlSetTip(-1, "Blacklist for donating Golems")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpWitches = GUICtrlCreateGroup("Witches", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateWitches = GUICtrlCreateIcon($pIconLib, $eIcnDonWitch, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateWitches = GUICtrlCreateCheckbox("Donate Witches", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Witches if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateWitches")
		$chkDonateAllWitches = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Witches to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllWitches")
		$lblDonateWitches = 	GUICtrlCreateLabel("Keywords for donating Witches:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateWitches = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("witches\r\nwitch"))
			GUICtrlSetTip(-1, "Keywords for donating Witches")
		$lblBlacklistWitches = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistWitches = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no witches\r\nwitch no"))
			GUICtrlSetTip(-1, "Blacklist for donating Witches")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpLavaHounds = GUICtrlCreateGroup("Lava Hounds", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateLavaHounds = GUICtrlCreateIcon($pIconLib, $eIcnDonLavaHound, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateLavaHounds = GUICtrlCreateCheckbox("Donate Lava Hounds", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Lava Hounds if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateLavaHounds")
		$chkDonateAllLavaHounds = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Lava Hounds to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllLavaHounds")
		$lblDonateLavaHounds = 	GUICtrlCreateLabel("Keywords for donating Lava Hounds:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateLavaHounds = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("lavahound\r\nhound\r\nlava"))
			GUICtrlSetTip(-1, "Keywords for donating Lava Hounds")
		$lblBlacklistLavaHounds = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistLavaHounds = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no lavahound\r\nhound no"))
			GUICtrlSetTip(-1, "Blacklist for donating Lava Hounds")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	;;; Custom Combination Donate by ChiefM3, edit by Hervidero
	$grpCustom = GUICtrlCreateGroup("Custom Troops", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom = GUICtrlCreateIcon($pIconLib, $eIcnDonCustom, $x + 215, $y, 64, 64, $BS_ICON)
		    GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateCustom = GUICtrlCreateCheckbox("Donate Custom Troops", $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Custom Troops if keywords match the Chat Request.")
			GUICtrlSetOnEvent(-1, "chkDonateCustom")
		$chkDonateAllCustom = GUICtrlCreateCheckbox("Donate to All", $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, "Check this to donate Custom Troops to ALL Chat Requests." & @CRLF & "This will also ignore ALL keywords.")
			GUICtrlSetOnEvent(-1, "chkDonateAllCustom")
		$lblDonateCustom =     GUICtrlCreateLabel("Keywords for donating Custom Troops:", $x - 5, $y + 90, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom = GUICtrlCreateEdit("", $x - 5, $y + 105, 205, 50, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("any\r\nneed"))
			GUICtrlSetTip(-1, "Keywords for donating Custom Troops")

		$lblDonateCustom1 = GUICtrlCreateLabel("1st:", $x, $y + 4, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom1 = GUICtrlCreateIcon($pIconLib, $eIcnDonWizard, $x + 25, $y, 24, 24)
			GUICtrlSetState(-1, $GUI_HIDE)
		$cmbDonateCustom1 = GUICtrlCreateCombo("", $x + 60, $y, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
			GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Wall Breakers|Balloons|Wizards|Healers|Dragons|Pekka's|Minions|Hog Riders|Valkyries|Golems|Witches|Lava Hounds|Nothing", "Wizards")
			GUICtrlSetOnEvent(-1, "cmbDonateCustom")
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom1 = GUICtrlCreateInput("2", $x + 165, $y, 30, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
			GUICtrlSetLimit(-1, 1)
			GUICtrlSetState(-1, $GUI_HIDE)

		$lblDonateCustom2 = GUICtrlCreateLabel("2nd:", $x, $y + 29, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom2 = GUICtrlCreateIcon($pIconLib, $eIcnDonArcher, $x + 25, $y + 25, 24, 24)
			GUICtrlSetState(-1, $GUI_HIDE)
		$cmbDonateCustom2 = GUICtrlCreateCombo("", $x + 60, $y + 25, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
			GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Wall Breakers|Balloons|Wizards|Healers|Dragons|Pekka's|Minions|Hog Riders|Valkyries|Golems|Witches|Lava Hounds|Nothing", "Archers")
			GUICtrlSetOnEvent(-1, "cmbDonateCustom")
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom2 = GUICtrlCreateInput("3", $x + 165, $y + 25, 30, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
			GUICtrlSetLimit(-1, 1)
			GUICtrlSetState(-1, $GUI_HIDE)

		$lblDonateCustom3 = GUICtrlCreateLabel("3rd:", $x, $y + 54, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom3 = GUICtrlCreateIcon($pIconLib, $eIcnDonBarbarian, $x + 25, $y + 50, 24, 24)
			GUICtrlSetState(-1, $GUI_HIDE)
		$cmbDonateCustom3 = GUICtrlCreateCombo("", $x + 60, $y + 50, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
			GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Wall Breakers|Balloons|Wizards|Healers|Dragons|Pekka's|Minions|HogRiders|Valkyries|Golems|Witches|Lava Hounds|Nothing", "Barbarians")
			GUICtrlSetOnEvent(-1, "cmbDonateCustom")
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom3 = GUICtrlCreateInput("1", $x + 165, $y + 50, 30, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
			GUICtrlSetLimit(-1, 1)
			GUICtrlSetState(-1, $GUI_HIDE)

		$lblBlacklistCustom = GUICtrlCreateLabel("Do NOT donate to these keywords:", $x + 215, $y + 90, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistCustom = GUICtrlCreateEdit("", $x + 215, $y + 105, 200, 50, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("only\r\njust"))
			GUICtrlSetTip(-1, "Blacklist for donating Custom Troops")
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpBlacklist = GUICtrlCreateGroup("General Blacklist", $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateBlacklist = GUICtrlCreateIcon($pIconLib, $eIcnDonBlacklist, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$lblBlacklist = GUICtrlCreateLabel("Do NOT donate to any of these keywords:", $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklist = GUICtrlCreateEdit("", $x -5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("clan war\r\nwar\r\ncw"))
			GUICtrlSetTip(-1, "General Blacklist for donation requests")
	GUICtrlCreateGroup("", -99, -99, 1, 1)
